fix(2d): can not update wrold position for sprite renderer when call …
oasis-engine/engine pull request #635
Opened 2022-01-17 11:08 UTC by singlecoder

…bounds in the same frame

### Please check if the PR fulfills these requirements

- [ ] The commit message follows our [guidelines](https://github.com/oasis-engine/engine/blob/main/.github/COMMIT_MESSAGE_CONVENTION.md)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

2022-03-02 09:21 UTC, cptbtptpbcptdtptp requested changes
SrpiteRenderer 克隆的时候需要考虑 _spriteDirty.

2022-03-03 03:06 UTC, GuoLei1990 commented on packages/core/src/2d/sprite/SpriteRenderer.ts
> +    if (this._isWorldMatrixDirty.flag || this._spriteDirty.flag || this._isContainDirtyFlag(DirtyFlag.Sprite)) {
If we use `this._spriteDirty.flag`, `this._isContainDirtyFlag(DirtyFlag.Sprite)` is no need!

2022-03-03 03:06 UTC, GuoLei1990 commented on packages/core/src/2d/sprite/SpriteRenderer.ts
> +    sprite._updateMeshData();
Use `_updateMesh()` and delete `_updateMeshData()`

2022-03-03 03:35 UTC, GuoLei1990 commented on packages/core/src/2d/sprite/SpriteRenderer.ts
> +  private _dirtyFlag: number = DirtyFlag.Flip;
I think the init value is 0

2022-03-03 06:26 UTC, GuoLei1990 approved these changes
+1

2022-03-03 06:48 UTC, cptbtptpbcptdtptp approved these changes
+1

2022-03-03 07:07 UTC, merged