Optimization texture struct
oasis-engine/engine pull request #715
Opened 2022-03-29 09:42 UTC by GuoLei1990

### Please check if the PR fulfills these requirements

- [x] The commit message follows our [guidelines](https://github.com/oasis-engine/engine/blob/main/.github/COMMIT_MESSAGE_CONVENTION.md)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

2022-03-30 03:25 UTC, singlecoder approved these changes
+1

2022-03-30 03:25 UTC, zhuxudong requested changes

2022-03-30 03:25 UTC, zhuxudong commented on packages/rhi-webgl/src/GLTextureCubeMap.ts
> +import { IPlatformTextureCubeMap, Logger, TextureCubeFace, TextureCube, TextureFormat } from "@oasis-engine/core";
rename this file to `GLTextureCube` is better

2022-03-30 03:25 UTC, zhuxudong commented on packages/rhi-webgl/src/GLRenderTarget.ts
> +    debugger;
???

2022-03-30 06:06 UTC, zhuxudong requested changes
`GLRenderColorTexture` , `RenderBufferDepthFormat`, `createPlatformTextureCubeMap` still have leftovers

2022-03-30 06:09 UTC, zhuxudong requested changes

2022-03-30 06:09 UTC, zhuxudong commented on packages/core/src/texture/RenderTarget.ts
> +    }
if(this.autoGenerateMipmaps){
... foreach colortexture
... depth texture

}

2022-03-30 06:36 UTC, zhuxudong commented on packages/loader/src/EnvLoader.ts
> +  ResourceManager, TextureCube, TextureCubeFace, TextureFilterMode
format code

2022-03-30 06:51 UTC, zhuxudong requested changes
`format` can move to `Texture` now

2022-03-30 07:00 UTC, GuoLei1990 commented on packages/loader/src/EnvLoader.ts
> +  ResourceManager, TextureCube, TextureCubeFace, TextureFilterMode
done

2022-03-30 07:50 UTC, GuoLei1990 commented
> `format` can move to `Texture` now

done

2022-03-30 10:13 UTC, zhuxudong requested changes

2022-03-30 10:13 UTC, zhuxudong commented on packages/rhi-webgl/src/GLRenderTarget.ts
> +    if (!GLTexture._supportRenderBufferDepthFormat(_depth, rhi, _depth instanceof Texture)) {
you must ensure `_depth` is `format` rather than `texture`

2022-03-31 03:03 UTC, zhuxudong approved these changes
+1

2022-03-31 03:18 UTC, merged