fix: physcis event remove when collider shape destroy
oasis-engine/engine pull request #738
Opened 2022-04-13 03:48 UTC by yangfengzzz

### Please check if the PR fulfills these requirements

- [ ] The commit message follows our [guidelines](https://github.com/oasis-engine/engine/blob/main/.github/COMMIT_MESSAGE_CONVENTION.md)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

### What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)

### What is the current behavior? (You can also link to an open issue here)

### What is the new behavior (if this is a feature change)?

### Does this PR introduce a breaking change? (What changes might users need to make in their application due to this PR?)

### Other information:

2022-04-13 08:08 UTC, cptbtptpbcptdtptp requested changes

2022-04-13 08:08 UTC, cptbtptpbcptdtptp commented on packages/physics-lite/src/LitePhysicsManager.ts
> +        event.state = TriggerEventState.Exit;
Unnecessary.

2022-04-13 08:20 UTC, cptbtptpbcptdtptp requested changes

2022-04-13 08:20 UTC, cptbtptpbcptdtptp commented on packages/physics-lite/src/LitePhysicsManager.ts
> +
``` 
  const { _eventPool: eventPool, _currentEvents: currentEvents } = this;
  const { _id: shapeID } = colliderShape;
  for (let i = currentEvents.length - 1; i >= 0; i--) {
    const event = currentEvents.get(i);
    if (event.index1 === shapeID || event.index2 === shapeID) {
      currentEvents.deleteByIndex(i);
      eventPool.push(event);
    }
  }
  delete this._eventMap[shapeID];
```

2022-04-13 08:20 UTC, cptbtptpbcptdtptp commented on packages/physics-physx/src/PhysXPhysicsManager.ts
> +
```
  const { _eventPool: eventPool, _currentEvents: currentEvents } = this;
  const { _id: shapeID } = colliderShape;
  for (let i = currentEvents.length - 1; i >= 0; i--) {
    const event = currentEvents.get(i);
    if (event.index1 === shapeID || event.index2 === shapeID) {
      currentEvents.deleteByIndex(i);
      eventPool.push(event);
    }
  }
  delete this._eventMap[shapeID];
```

2022-04-14 01:53 UTC, yangfengzzz commented on packages/physics-lite/src/LitePhysicsManager.ts
> +
done

2022-04-14 01:53 UTC, yangfengzzz commented on packages/physics-physx/src/PhysXPhysicsManager.ts
> +
done

2022-04-14 02:44 UTC, GuoLei1990 approved these changes
+1

2022-04-14 03:13 UTC, cptbtptpbcptdtptp approved these changes
+1

2022-04-14 03:14 UTC, merged