Add component denpendent decorator
oasis-engine/engine pull request #796
Opened 2022-05-11 06:45 UTC by GuoLei1990

### Please check if the PR fulfills these requirements

- [x] The commit message follows our [guidelines](https://github.com/oasis-engine/engine/blob/main/.github/COMMIT_MESSAGE_CONVENTION.md)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

2022-05-12 06:49 UTC, yangfengzzz requested changes

2022-05-12 06:49 UTC, yangfengzzz commented on packages/core/src/physics/Collider.ts
>   * Abstract class for collider shapes.
Collider also relay on Transform

2022-05-13 10:15 UTC, GuoLei1990 commented on packages/core/src/physics/Collider.ts
>   * Abstract class for collider shapes.
done

2022-05-16 03:07 UTC, yangfengzzz approved these changes
+1

2022-05-16 06:00 UTC, gz65555 approved these changes

2022-05-16 06:03 UTC, merged