fix: prevent TypeError: Cannot read property '_target' of undefined while 'maxJoints' is too small
oasis-engine/engine pull request #82
Opened 2021-03-02 08:14 UTC by colorhook

### Please check if the PR fulfills these requirements

- [x] The commit message follows our [guidelines](https://github.com/oasis-engine/engine/blob/main/.github/COMMIT_MESSAGE_CONVENTION.md)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

### What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)

修复官方「骨骼动画」demo 在有些平台抛出的 TypeError 异常

### What is the current behavior? (You can also link to an open issue here)

### What is the new behavior (if this is a feature change)?

### Does this PR introduce a breaking change? (What changes might users need to make in their application due to this PR?)

No

### Other information:

2021-03-02 08:49 UTC, zhuxudong requested changes

2021-03-02 08:49 UTC, zhuxudong commented on packages/core/src/mesh/SkinnedMeshRenderer.ts
> +          this.createJointTexture();
这里的确修复了 bug，但是会多执行一次 `setPixelBuffer`，可以将 `setTexture` 等操作放到 `createJointTexture` 中执行

2021-03-02 09:52 UTC, colorhook commented on packages/core/src/mesh/SkinnedMeshRenderer.ts
> +          this.createJointTexture();
已根据建议优化并验证

2021-03-03 02:45 UTC, GuoLei1990 approved these changes

2021-03-03 02:54 UTC, zhuxudong commented on packages/core/src/mesh/SkinnedMeshRenderer.ts
> +          this.createJointTexture();
还有点小问题，给您提 PR了：https://github.com/colorhook/oasis-engine/pull/1

2021-03-03 06:24 UTC, colorhook commented on packages/core/src/mesh/SkinnedMeshRenderer.ts
> +          this.createJointTexture();
666

2021-03-03 09:09 UTC, zhuxudong approved these changes

2021-03-03 09:09 UTC, merged